### PR TITLE
More Icons , Compose & Kotlin Updates , Search Icons in Demo App

### PR DESCRIPTION
**Pull request by wakaztahir**
- Update Project
- Kotlin,Compose
- Add MaterialDesignIcons
- Merge Android & Jetbrains Compose
- Add Demo App
- Add Web Target

You must update the version and then publish it , It will require a lot of time to build , since MaterialDesignIcons has more than 7000 icons

I have merged Jetbrains and Jetpack Compose Releases , Now common libraries are under "jetbrains" group name , upgraded gradle & project configuration and the signing/publishing configuration is same , A Web target has been added.
I added a demo app as well

- This allows user to search through icons with the demo app , copy the code / dependency to use it
- I have updated each icons provider to latest version , making  a lot of more icons

### CODE REVIEW

**Comment by wakaztahir** [comment]
I have made these  changes to my fork

- Integrated Converter
I have copied Android Studio classes to convert the icons to Drawable and SVG to create a module that converts the icons

- Demo App Changes
I have created a demo app which allows user to provide all the parameters of Svg2Compose parse function and it converts the user provided icons to jetpack compose , The UI is in compose

I won't be making another pull request , Please merge this pull request and reply here so I can make another pull request and merge that one as well. I have changed a little publishing information which is causing me a little headache but I'll fix it.

**Comment by DevSrSouza** [comment]
Can you also comment images and gifs of the app?

**Comment by wakaztahir** [comment]
The app works , I've tested it , in the debug version

capture-2
er-images.githubusercontent.com/42442700/213439835-2d480862-7caf-45bd-91a5-efe84cc32813.PNG)

**Comment by wakaztahir** [comment]
Everything is compose multiplatform EXCEPT the converter which has some java classes , I might eliminate them , we could literally post it online / anywhere after that but that's a little far from now !

**Comment by wakaztahir** [comment]
seems like this pull request does contain new commits , its a little unfinished. can you please publish the new release (I need those icons)

The release MSI gives this error due to proguard , I have installed the debug msi to search icons , its around 150mbs
https://github.com/JetBrains/compose-jb/issues/2650
I have reported it , Its caused by some icon files made by fluentui-system-icons or jetpack compose or proguard bug

Things to do before release

- The newer commits remove the ".jetbrains" in the group id and I also made huge changes to gradle files , the problem is that when I use the library in another app , its not getting the icons , You must fix this before releasing the new version of the icons , basically the release configuration

**Comment by wakaztahir** [comment]
[5e9f314](https://github.com/DevSrSouza/compose-icons/pull/24/commits/5e9f314c61cb71d380026d2386613062857d8f5c)

I did't go through with this commit , I had to revert creating a map inside .kts files , because I realised ImageVector has a name property , so most of the files are unchanged

**Comment by DevSrSouza** [comment]
Can you create small Pull Request? For each change.
For example, Multiple PRs for each new icon pack, update gradle configuration and all dependencies versions, uniting jetbrains and android targets, creating the sample/converter application (demo app).

I willing to get all this contribution of yours and open small pull request and increment things I want for the project as well.

**Comment by DevSrSouza** [comment]
Also I pretend to replace the way I publish/generate icons by having the generated source at build folder and having [binary-compatibility-validator](https://github.com/Kotlin/binary-compatibility-validator) commited

**Comment by DevSrSouza** [comment]
The source code of the project it huge, the PR got huge because of the new icons and this make impossible to review.

**Pull request closed without merging**
